[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "api-rest-dj"
authors = [{name = "Randy", email = "randy930529@gmail.com"}]
dynamic = ["version", "description"]
